[[build]]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"

[functions]
  node_bundler = "esbuild"
  directory = "netlify/functions"

# Scheduled Functions
[[functions]]
  path = "/crawl-topic"
  schedule = "5 * * * *"  # Hourly at 5 minutes past

[[functions]]
  path = "/discovery-probe"
  schedule = "0 3 * * *"  # Daily at 3:00 AM UTC

# Redirects for Next.js
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/:splat"
  status = 200
  conditions = {Role = ["api"]}
