[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20.11.0"

[functions]
  node_bundler = "esbuild"
  directory = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-nextjs"
