name: Weekly Points Decay

on:
  schedule:
    # Run every Sunday at 2:00 AM UTC
    - cron: '0 2 * * 0'
  workflow_dispatch: # Allow manual trigger

jobs:
  decay:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Run weekly decay
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          node -e "
          const { weeklyDecay } = require('./src/lib/sources');
          weeklyDecay().then(() => console.log('Decay complete'));
          "
